### ISSUE TITLE
Support for BestServers.com

### ISSUE THREAD

**Issue by byluz** [Murgator/FiveM-vote-script#4]
Hello, I am wondering if I could get support for the gaming top server list https://bestservers.com ? Their docs are located at https://bestservers.com/documentation

Thanks!

**Comment by Murgator** [comment]
I will see it soon thank you for your suggestion !

**Comment by byluz** [comment]
> I will see it soon thank you for your suggestion !

Cool cool, yes please take a look at let me know!

**Comment by Murgator** [comment]
sorry but I cannot adapt the script because the api does not work the same

**Comment by byluz** [comment]
Okay, if you can let me know what you need from the api then I can work on supporting that. Thanks

**Comment by byluz** [comment]
My API has server key and username being used. Would I need to update to be able for you get grab the server id?
https://bestservers.com/documentation
