### ISSUE TITLE
[QBCore] Fresh install with error

### ISSUE THREAD

**Issue by Graxo** [Murgator/FiveM-vote-script#7]
Hi, i just installed the script and filled in my server id and key.
When a player uses /vote in-game i get the following error in the console:
[script:FiveM-vote-sc] SCRIPT ERROR: @FiveM-vote-script-master/server/server.lua:31: bad argument #2 to 'format' (number expected, got string)
[script:FiveM-vote-sc] > ref (@FiveM-vote-script-master/server/server.lua:31)

I hope this can be fixed. If you need more info, feel free to contact me.

Greetings,
Graxo

**Comment by Murgator** [comment]
Hi Graxo sorry for the wait time, the problem has been solved. I advise you to download all the script and the configuration file.

Cordially,
Murgator
